### ISSUE TITLE
Protocol file not written

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/RadiAID#14]
Guess that's self-explanatory.

**Comment by jo-mueller** [comment]
Fixed in commit 40865c85162ce969501e73ecc7d2ec5b10cca0d4

**Comment by jo-mueller** [comment]
I added a screenshot and a folder selection dialog to the report generation (5afa9e2a6515d8c4e4d615d8c3ec57c35adfe519 ). That should suffice for all documentation purposes.
